spring:
  kafka:
    topic: ${KAFKA_TOPIC:test}                      # default: "test"
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}    # required: injected from env
  data:
    mongodb:
      uri: ${MONGO_URI}                              # required: injected from env