spring:
  application:
    name: User Service
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: WARN
  file:
    name: logs/user-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
info:
  app:
    name: Test Project
    description: This is a user service app
    version: 1.0.0