# NOTE:
# This workflow is intended **only for test/CI purposes**.
# It compiles and builds your project, skipping integration tests.
#
# For actual deployment, Docker build, or production workflows,
# you should create separate workflows with:
#   - Docker build/push steps
#   - Deployment steps (to your cloud/cluster/etc.)
#   - Full test runs (including integration tests if needed)
# --------------------------------------------------------
name: Build (No Integration Tests)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven (skip integration tests)
        run: mvn clean install -DskipITs